<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Numo.DevServices.Api</RootNamespace>
        <AssemblyName>Numo.DevServices.Api</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2"/>
        <PackageReference Include="Numo.Core.Application" Version="7.0.248"/>
        <PackageReference Include="Numo.Core.Domain" Version="7.0.248"/>
        <PackageReference Include="Numo.Core.Host.AspNetCore" Version="7.0.248"/>
        <PackageReference Include="Numo.Core.Infrastructure" Version="7.0.248"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="appsettings.*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="appsettings.Development.Template.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
        <Content Remove="ClientApp\**"/>
        <None Remove="ClientApp\node_modules\**"/>
    </ItemGroup>

</Project>
